import pandas as pd


def company_summary(df):
    """
    Calculate total emissions for each company.
    """

    summary = (
        df.groupby("company", as_index=False)
        .agg(
            scope_1_tco2e=("scope_1_tco2e", "sum"),
            scope_2_tco2e=("scope_2_tco2e", "sum"),
            scope_3_tco2e=("scope_3_tco2e", "sum"),
            total_tco2e=("total_tco2e", "sum"),
        )
    )

    return summary


def yearly_summary(df):
    """
    Calculate total emissions for each year.
    """

    summary = (
        df.groupby("year", as_index=False)
        .agg(
            scope_1_tco2e=("scope_1_tco2e", "sum"),
            scope_2_tco2e=("scope_2_tco2e", "sum"),
            scope_3_tco2e=("scope_3_tco2e", "sum"),
            total_tco2e=("total_tco2e", "sum"),
        )
    )

    return summary


def scope_summary(df):
    """
    Calculate total emissions by emission scope.
    """

    return pd.DataFrame(
        {
            "scope": [
                "Scope 1",
                "Scope 2",
                "Scope 3",
            ],
            "emissions_tco2e": [
                df["scope_1_tco2e"].sum(),
                df["scope_2_tco2e"].sum(),
                df["scope_3_tco2e"].sum(),
            ],
        }
    )


def calculate_carbon_intensity(df):
    """
    Calculate carbon intensity metrics.

    Metrics:
        - tCO2e per $1 million revenue
        - tCO2e per employee
    """

    result = df.copy()

    result["tco2e_per_million_usd"] = (
        result["total_tco2e"]
        / result["revenue_million_usd"]
    )

    result["tco2e_per_employee"] = (
        result["total_tco2e"]
        / result["employees"]
    )

    return result


def top_emission_sources(df):
    """
    Calculate emissions generated by individual activity sources.
    """

    sources = pd.DataFrame(
        {
            "source": [
                "Diesel",
                "Natural Gas",
                "Electricity",
                "Business Travel",
                "Employee Commute",
                "Waste",
            ],
            "emissions_tco2e": [
                df["diesel_emissions_kg"].sum() / 1000,
                df["natural_gas_emissions_kg"].sum() / 1000,
                df["electricity_emissions_kg"].sum() / 1000,
                df["business_travel_emissions_kg"].sum() / 1000,
                df["employee_commute_emissions_kg"].sum() / 1000,
                df["waste_emissions_kg"].sum() / 1000,
            ],
        }
    )

    return sources.sort_values(
        "emissions_tco2e",
        ascending=False
    ).reset_index(drop=True)


def calculate_kpis(df):
    """
    Calculate high-level ESG dashboard KPIs.
    """

    return {
        "total_emissions": df["total_tco2e"].sum(),
        "scope_1": df["scope_1_tco2e"].sum(),
        "scope_2": df["scope_2_tco2e"].sum(),
        "scope_3": df["scope_3_tco2e"].sum(),
        "companies": df["company"].nunique(),
        "years": df["year"].nunique(),
    }